---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/workload: mainnet-mainnet-ckb-monitor
  labels:
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: mainnet-mainnet-ckb-monitor
  name: mainnet-mainnet-ckb-monitor
  namespace: mainnet
  resourceVersion: '91784199'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: monitor
      k8s.kuboard.cn/name: mainnet-mainnet-ckb-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-04-15T23:50:54+08:00'
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: monitor
        k8s.kuboard.cn/name: mainnet-mainnet-ckb-monitor
    spec:
      containers:
        - env:
            - name: CKB_RPC_URL
              value: 'http://mainnet-ckb:8114'
            - name: UPDATE_INTERVAL
              value: '5'
          image: 'ghcr.io/magickbase/ckb-node-monitor:v0.0.4'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: ckb-node-monitor
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: mainnet-mainnet-ckb-monitor
  labels:
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: mainnet-mainnet-ckb-monitor
  name: mainnet-mainnet-ckb-monitor
  namespace: mainnet
spec:
  ports:
    - name: ipphzz
      nodePort: 30115
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: mainnet-mainnet-ckb-monitor
  sessionAffinity: None
  type: NodePort
